/* generated by scripts/build-posts.mjs. do not edit by hand. */
window.POSTS = [
  {
    "slug": "prompt-compression",
    "title": "Notes on prompt compression",
    "date": "2026-03-02",
    "excerpt": "The small tricks that took a third off our token bill.",
    "image": ""
  },
  {
    "slug": "search-stack",
    "title": "Why we rebuilt our search stack",
    "date": "2026-02-14",
    "excerpt": "What we learned replacing keyword search with a hybrid of BM25 and vectors.",
    "image": "assets/blog/search-stack.png"
  },
  {
    "slug": "whisper-and-llama",
    "title": "A weekend with Whisper and Llama",
    "date": "2025-11-08",
    "excerpt": "Building a voice agent that never leaves the laptop.",
    "image": ""
  }
];
