/* generated by scripts/build-posts.mjs. do not edit by hand. */
window.POSTS = [
  {
    "slug": "intro-to-llms",
    "title": "Intro to LLMs",
    "date": "2026-09-14",
    "excerpt": "A basic overview of LLM architecture.",
    "image": ""
  },
  {
    "slug": "pilot",
    "title": "Pilot",
    "date": "2026-09-14",
    "excerpt": "Episode 1",
    "image": ""
  }
];
