/* generated by scripts/build-posts.mjs. do not edit by hand. */
window.POSTS = [
  {
    "slug": "intro-to-llms",
    "title": "Intro to LLMs",
    "date": "2026-09-14",
    "excerpt": "While many use it regularly, they may not know the inner workings of LLMs. On a high-level, LLMs are autoregressive models, meaning that the",
    "image": ""
  },
  {
    "slug": "pilot",
    "title": "Pilot",
    "date": "2026-09-14",
    "excerpt": "Episode 1",
    "image": ""
  }
];
