/* ==========================================================================
   scripts/build-posts.mjs
   --------------------------------------------------------------------------
   Reads every markdown file under posts/, at any depth, and writes posts.js,
   the manifest the site loads. Run it by hand with `npm run build:posts`, or
   let `npm run edit` do it when you save a post.

   A folder under posts/ is a category:
     posts/pilot.md                no category
     posts/llms/intro-to-llms.md   the LLMs category
   and front matter can name it outright with `category:`, which is what you
   want when the folder name is a slug and the label should read nicely.
   ========================================================================== */

import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const postsDir = path.join(root, "posts");

/* front matter is a small block between two --- lines */
export function parseFrontMatter(raw) {
  const meta = {};
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) return { meta, body: raw };

  match[1].split("\n").forEach((line) => {
    const at = line.indexOf(":");
    if (at < 1) return;
    const key = line.slice(0, at).trim();
    let value = line.slice(at + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    meta[key] = value;
  });

  return { meta, body: match[2] };
}

export function toSlug(title) {
  return String(title)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "post";
}

/* every markdown file under posts/, as a path relative to posts/ */
export async function postFiles() {
  async function walk(dir, prefix) {
    let entries = [];
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch (e) {
      return [];
    }

    let found = [];
    for (const entry of entries) {
      if (entry.name.startsWith(".")) continue;
      const rel = prefix ? prefix + "/" + entry.name : entry.name;
      if (entry.isDirectory()) found = found.concat(await walk(path.join(dir, entry.name), rel));
      else if (entry.name.endsWith(".md")) found.push(rel);
    }
    return found;
  }

  return (await walk(postsDir, "")).sort();
}

export async function buildPosts() {
  const posts = [];

  for (const rel of await postFiles()) {
    const raw = await readFile(path.join(postsDir, rel), "utf8");
    const { meta, body } = parseFrontMatter(raw);
    const slug = rel.replace(/\.md$/, "");
    const folder = slug.split("/").slice(0, -1).join(" / ");
    const category = String(meta.category || folder || "").trim();

    posts.push({
      slug,
      title: meta.title || slug.split("/").pop(),
      date: meta.date || "",
      excerpt: meta.excerpt || firstLine(body),
      image: meta.image || "",
      category,
      categoryKey: category ? toSlug(category) : ""
    });
  }

  posts.sort(
    (a, b) => String(b.date).localeCompare(String(a.date)) || a.title.localeCompare(b.title)
  );

  const out =
    "/* generated by scripts/build-posts.mjs. do not edit by hand. */\n" +
    "window.POSTS = " +
    JSON.stringify(posts, null, 2) +
    ";\n";

  await writeFile(path.join(root, "posts.js"), out);
  return posts;
}

function firstLine(body) {
  const line = String(body)
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("#") && !l.startsWith(">") && !l.startsWith("-"))[0];
  return line ? line.replace(/[*`]/g, "").slice(0, 140) : "";
}

if (process.argv[1] && process.argv[1].endsWith("build-posts.mjs")) {
  const posts = await buildPosts();
  console.log("posts.js written with " + posts.length + " post" + (posts.length === 1 ? "" : "s"));
}
